/*!
 * jsTodoTxt Library v0.1.0
 * https://github.com/jmhobbs/jsTodoTxt
 *
 * Copyright 2011, John Hobbs
 * Licensed under the MIT license.
 * https://github.com/jmhobbs/jsTodoTxt/blob/master/LICENSE
 */
var TodoTxt={_trim_re:/^\s+|\s+$/g,_complete_replace_re:/^x\s*/i,_date_re:/^([0-9]{4}-[0-9]{1,2}-[0-9]{1,2})/,_date_replace_re:/^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}\s*/,_priority_re:/\(([A-Z])\)/,_priority_replace_re:/\s*\([A-Z]\)\s*/,_location_re:/@(\S+)/,_location_replace_re:/\s*@\S+\s*/,_project_re:/\+(\S+)/,_project_replace_re:/\s*\+\S+\s*/,parse:function(c){var b=[];var a=c.split("\n");for(i in a){b.push(new TodoTxtItem(a[i]))}return b},parseLine:function(a){return new TodoTxtItem(a)},render:function(b){var a=[];for(i in b){a.push(b[i].toString())}return a.join("\n")},renderItem:function(a){return a.toString()}};function TodoTxtItem(a){this.text=null;this.priority=null;this.complete=false;this.date=null;this.location=null;this.project=null;this.toString=function(){var b=this.text;if(null!=this.priority){b="("+this.priority+") "+b}if(null!=this.date){b=this.date+" "+b}if(this.complete){b="x "+b}if(null!=this.project){b=b+" +"+this.project}if(null!=this.location){b=b+" @"+this.location}return b};this.parse=function(b){b=b.replace(TodoTxt._trim_re,"");b=b.replace("\r","");if(b[0]=="x"||b[0]=="X"){this.complete=true;b=b.replace(TodoTxt._complete_replace_re,"")}var c=TodoTxt._date_re.exec(b);if(null!=c){this.date=c[1];b=b.replace(TodoTxt._date_replace_re,"")}var d=TodoTxt._priority_re.exec(b);if(null!=d){this.priority=d[1];b=b.replace(TodoTxt._priority_replace_re,"")}var f=TodoTxt._location_re.exec(b);if(null!=f){this.location=f[1];b=b.replace(TodoTxt._location_replace_re," ")}var e=TodoTxt._project_re.exec(b);if(null!=e){this.project=e[1];b=b.replace(TodoTxt._project_replace_re," ")}b=b.replace(TodoTxt._trim_re,"");this.text=b};if("string"==typeof(a)){this.parse(a)}};
